### ISSUE TITLE
Floating labels

### ISSUE THREAD

**Issue by nam-co** [Okipa/laravel-bootstrap-components#1]
Hi Arthur, thanks for the package, looking good, I was wondering what is the best/easiest way to do something like Floating labels, example: https://getbootstrap.com/docs/4.1/examples/floating-labels/

Thanks

**Comment by Okipa** [comment]
@nam-co Hi and thanks for your encouragements.

I think this is possible to implement this without so much pain.
I will take a look about this when I'll have some free time.
Big rush @ work right now.

If you need it quickly, feel free to send a full tested PR on one component for example. If i'm ok with it, it can give me a base to implement this on the others.

**Comment by Okipa** [comment]
HI @nam-co, as this feature is still considered as an experiment by the Bootstrap team itself, I will not implement it for the moment into this package.  
But you easily can customize the package views to get each component being designed as you want them to be.  
I will consider this feature differently when the feature will be released as a stable one.
