### ISSUE TITLE
Published views not used

### ISSUE THREAD

**Issue by daniel-chris-lucas** [Okipa/laravel-bootstrap-components#3]
- Laravel Version: 5.7.13
- PHP Version: 7.2.12
- Database Driver & Version: MySQL 5.7.24

### Description:

When publishing the views to customizing them using the `php artisan vendor:publish --tag=bootstrap-components::views`, the views are not used.

### Steps To Reproduce:

Publish the views using the `php artisan vendor:publish --tag=bootstrap-components::views` command. When you modify a file in `resources/views/vendor/components/bootstrap-components` the changes are not reflected in the browser. The package keeps using the views in composer's vendor directory.

**Comment by Okipa** [comment]
Merge request accepted and published in : https://github.com/Okipa/laravel-bootstrap-components/releases/tag/0.5.7
