### ISSUE TITLE
onclick="myFunction()"

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#31]
how would you add this? I tried prepend, and I've tried others, but can't find one that works.

**Comment by Okipa** [comment]
There is currently no way to add proper inline javascript.  
You have to set custom id or classes and to write your scripts in dedicated js files.  
I would advise to proceed this way to allow resources caching for your scripts.

**Comment by fbc** [comment]
I'm trying to do something like this:

```
{{bsCheckbox()->name('other')->label('Other')->prepend('onclick="myFunction()"')}}
<div id="myDIV" style="display: none;">
            {{bsTextarea()->name('describe_others')->placeholder('(Ex. other')->label('Please describe other tiems in more detail.')}}
</div>
<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
```

so I think you are saying to try {{ bsTextarea()->containerId('myDIV')}} ??
and to manually create the checkbox button?

**Comment by Okipa** [comment]
you could do :

```blade
{{ bsTextarea()->name('description')->componentId('my-textarea') }}
```

And in your script :
```javascript
// jquery example
$('#my-textarea').on('whatever-event-you-want', () => {
    // some js actions
});
```
