### ISSUE TITLE
changing rows for bsTextarea()

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#36]
I've tried:
```
->containerHtmlAttributes('rows="40"'])
```
and
```
->componentHtmlAttributes('rows="40"'])
```
but they both error out. What am I doing wrong?

**Comment by Okipa** [comment]
Hi @fbc, these methods are both accepting an array for parameter.
You should call it like this : ->componentHtmlAttributes(["rows" => 40])
