### ISSUE TITLE
bsFile with array field same remove checkbox Id

### ISSUE THREAD

**Issue by yepzy** [Okipa/laravel-bootstrap-components#37]
The remove checkbox of bsFile use the name attribute to be generated and don't follow the id of the component.

So if I use few bsFile with an array field and custom the Component Id the remove checkbox will have the same Id on all bsFile of the array field.

Using the Id of the component (where default is the name) to generate the remove checkbox Id

**Comment by Okipa** [comment]
Closing as this is not an issue after investigation.  
This behaviour can be fixed by using array names like `name="name[1]"`, for example.
