### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#48]
I recently migrated to version 2 and replaced all old labels with the new ones.

I'm trying to use:
`
{{inputRadio()->name('no_insulation')->value('0')->label('No Insulation')->prepend('<i class="fas fa-times-circle"></i>')}}
`
but I'm getting:
`Okipa\LaravelBootstrapComponents\Components\Form\Radio : Missing $value property. Please use the value() method to set a value. (View: /home/user/LaravelProjects/estimator/resources/views/elevation/createroofelevation.blade.php) 
`
The value is being set, so i really don't understand why I'm getting the error.

**Comment by fbc** [comment]
The problem appears to be trying to use a value of 0. It works if you use anything other than zero.

**Comment by Okipa** [comment]
You should rather use the `->checked()` method with the `radio`, `checkbox` or the `toggle` component.

Using the `->value()` method is authorized but you should keep in mind that this component works with boolean.

If something is still breaking, could you PR a test putting the bug in evidence ? I'll start with this to check how to fix it.

**Comment by Okipa** [comment]
I'm closing this as there is no movements here.

However, an new tag has just been released with something that could interest you and that might be related to this issue : https://github.com/Okipa/laravel-bootstrap-components/releases/tag/2.1.3
