### ISSUE TITLE
Is there any way to change the checked/unchecked value of inputCheckbox() to 0/1 instead of off/on?

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#49]
Is there any way to change the checked/unchecked value of inputCheckbox() to 0/1 instead of off/on?

**Comment by Okipa** [comment]
I would say that it is a normal checkbox behavior. Checkboxes values are changing according to browsers. It sometime send `1` and sometimes `on`.

The better way to handle this seems to intercept this in your `FormRequest` and to cast it with `boolval()`.

```
    protected function prepareForValidation()
    {
        $this->merge(['active' => boolval($this->active)]);
    }
```
