### ISSUE TITLE
inputnumber not acepting decimals

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#51]
Is there anything I can do to make inputnumber accept decimals?

**Comment by Okipa** [comment]
You have to add a `step` HTML attribute, this is not related to this package but pure HTML : https://www.w3schools.com/tags/att_input_step.asp

However, you can add HTML attributes to the input number component with the `->componentHtmlAttributes()` method.

**Comment by fbc** [comment]
found it! Thanks.
->componentHtmlAttributes(['step' => "0.01"])}}
