### ISSUE TITLE
Feature Request: Lookahead searches

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#65]
It would be really great if you could optionally activate lookahead searches.

ex: To FORM ABSTRACT
    ->options(collect($search), 'id', 'title')->search(User::where('active', $x);

So when people start typing it begins searching for those fields. Your component would be only one doing it, built in; without any extra messy or cumbersome Javascript and routes to write. It could only make your component pratically the defacto standard when creating forms. People would then only use Laravel Collective when doing things that required a more custom approach.

**Comment by Okipa** [comment]
This kind of feature can't be implemented without javascript and the aim of this package is to generate all the complex HTML and let users implement their own solutions to improve the basic Bootstrap select provided.

Moreover, I think that embed such a feature in this package would be kind of reinventing the wheel when some solutions already exist and are really easy to use.

You could for exemple use [SumoSelect](http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html), or [Select2](https://github.com/select2/select2) to set this up.

If you are looking for an implementation example, you can check here how I managed to implement SumoSelect : https://github.com/ACID-Solutions/starter/blob/master/resources/js/scripts/common/utils/sumoselect.js

Then, I only have to call my select components like this to benefit from a search feature in my select:

```blade
{{ select()->name('category_ids')
    ->model($article)
    ->options((new App\Models\News\NewsCategory)->get(), 'id', 'name')
    ->multiple()
    ->componentClasses(['selector']) }}
```

**Comment by fbc** [comment]
Would it be possible to do something like:
```
{{ select()->name('category_ids')
    ->model($article)
    ->options((new App\Models\News\NewsCategory)->get(), 'id', 'first_name'.' '.'last_name')
    ->multiple()
    ->componentClasses(['selector']) }}
```
It would be really great if you can get it to match on more than on field. Or maybe a possible solution might be to alter the model
with something like:
```
public function getNameAttribute()
{
return $this-first_name." ".$this->last_name;
}
```
What do you think might be the best solution?
