### ISSUE TITLE
Line Breaks in placeholder field possible?

### ISSUE THREAD

**Issue by fbc** [Okipa/laravel-bootstrap-components#67]
I have a textarea for an address field and I would like to do something like:
->placeholder('Bob Smith<br/>123 main street<br/>city, state, zip')

 I tried:
->placeholder('Bob'.<br/>.'123 main street')
->placeholder('Bob'.'<br/>'.'123 main street')

I can't seem to make it work.

**Comment by Okipa** [comment]
Well, did you try to do this directly on a simple HTML textarea first? I'm not sure this is possible at all.

**Comment by Okipa** [comment]
I did a small research, it seems that it may be possible with JS hack but not displayed correctly in all browsers : https://stackoverflow.com/questions/7189223/can-you-have-multiline-html5-placeholder-text-in-a-textarea.

However, I close this as it is not related to this package but pure HTML thing.
